name: 'TiCS Github Action'
author: 'TIOBE'
description: 'Scan and analyse your codebase using TiCS'
inputs:
  projectName:  # id of input
    description: 'Name of the TICS project'
    required: true
  branchName:  # id of input
    description: 'Name of the branch in TICS'
    required: false
  branchDir:  # id of input
    description: 'Location of the files to analyze'
    required: false
  ticsViewerUrl:  # id of input
    description: 'URL to the TICS Viewer'
    required: true
  calc: # id of input
    description: 'Comma-separated list of metrics to be used'
    required: false
    default: 'ALL'
  ticsAuthToken:  # id of input
    description: 'Authentication token to connect to the TICS Viewer'
    required: false
  clientToken:  # id of input
    description: 'Reference ID for this specific run'
    required: false
  tmpDir:  # id of input
    description: 'Location to store debug information'
    required: false
branding:
  icon: 'flag'  
  color: 'blue'
runs:
  using: 'node12'
  main: 'index.js'