name: Build

on:
  pull_request: 
        types: [ opened, edited, synchronize, reopened ]

jobs:
  TiCSDemo-CI:
    name: TiCS
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Publish TICS
        uses: ./
        env: 
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          projectName: 'tics_action'                                        # mandatory, default value is the project name that this action is running on
          branchName: 'andriopoulou-danai-patch-1'                          # mandatory, default value is the branch name that this action is running on
          branchDir: '/home/danai/Tics-Plugins/tics_action'                 # mandatory
          ticsViewerUrl: 'http://localhost:20212/tiobeweb/2021.2/'          # mandatory
          clientToken: 'githubToken'
