name: Build

on:
  pull_request: 
        types: [ opened, edited, synchronize, reopened ]

jobs:
  TiCSDemo-CI:
    name: TiCS
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Publish TICS
        uses: ./
        env: 
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          projectName: 'js1'
          branchName: 'main'
          ticsViewerUrl: 'http://localhost:20221/tiobeweb/2022.1/'
          clientToken: 'danai'
          calc: 'CW,CS,FANOUT,CY,DUP'
          installTics: true
